apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-serviceaccount
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: my-serviceaccount
    namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: my-centos-pod
  namespace: default
spec:
  serviceAccountName: my-serviceaccount
  containers:
    - name: centos-container
      image: centos:latest
      command: ["/bin/bash", "-c", "--"]
      args: ["while true; do sleep 30; done;"]
